// This file defines what an "Event" looks like in our app.
// Think of it like a blueprint or a form with all the fields an event can have.

// We need this import to work with Firebase Timestamps
// Firebase stores dates differently than Dart, so we need to convert them
import 'package:cloud_firestore/cloud_firestore.dart';

// This is the EventModel class — it represents one event in our app
class EventModel {

  // --- All the fields (think of these as columns in a table) ---

  final String id;               // Unique ID of this event (auto-generated by Firestore)
  final String clubId;           // Which club organized this event
  final String tenureId;         // Which tenure (year period) this event belongs to
  final String name;             // Name of the event e.g. "Coding Hackathon 2025"
  final String description;      // A short description of what the event is about
  final DateTime date;           // When the event starts
  final DateTime endDate;        // When the event ends
  final double durationHours;    // How many hours the event ran e.g. 2.5
  final String venue;            // Where it was held e.g. "Seminar Hall A"
  final String type;             // Type: "workshop", "hackathon", "cultural", "seminar", "sports", "other"
  final int totalRegistrations;  // How many people registered for the event
  final int totalAttendees;      // How many people actually showed up
  final bool budgetClosed;       // Is the finance for this event finalized? false by default
  final DateTime? budgetClosedAt; // When was the budget closed — nullable (can be empty)
  final DateTime createdAt;      // When was this event record created in the app
  final String reportStatus; 
  // Values: 'draft', 'pending_review', 'needs_revision', 'approved'
final String reportRevisionNote;
// Admin's note when requesting revision — empty string by default

  // --- Constructor ---
  // This is called when we create a new EventModel object in our code
  EventModel({
    required this.id,
    required this.clubId,
    required this.tenureId,
    required this.name,
    required this.description,
    required this.date,
    required this.endDate,
    required this.durationHours,
    required this.venue,
    required this.type,
    required this.totalRegistrations,
    required this.totalAttendees,
    required this.budgetClosed,
    this.budgetClosedAt,          // Not required because it can be null
    required this.createdAt,
    required this.reportStatus,
    required this.reportRevisionNote,
  });

  // --- fromJson ---
  // This is a factory constructor — it builds an EventModel FROM Firestore data
  // "json" here is a Map (like a dictionary) that Firestore gives us
  // We also pass the document id separately because Firestore doesn't include it in the data map
  factory EventModel.fromJson(String id, Map<String, dynamic> json) {
    return EventModel(
      id: id, // The document ID from Firestore

      // Use ?? to provide a fallback if the field is missing or null
      clubId: json['clubId'] ?? '',
      tenureId: json['tenureId'] ?? '',
      name: json['name'] ?? '',
      description: json['description'] ?? '',

      // Firestore stores dates as Timestamps — we convert them to Dart DateTime
      // (json['date'] as Timestamp) casts the value to a Timestamp object
      // .toDate() then converts it to a normal Dart DateTime
      date: _parseDate(json['date']),
      endDate: _parseDate(json['endDate']),

      // Convert to double — Firestore may store this as int or double
      durationHours: (json['durationHours'] ?? 0).toDouble(),

      venue: json['venue'] ?? '',
      type: json['type'] ?? 'other',

      // Convert to int safely
      totalRegistrations: (json['totalRegistrations'] ?? 0).toInt(),
      totalAttendees: (json['totalAttendees'] ?? 0).toInt(),

      // Convert to bool — defaults to false if missing
      budgetClosed: json['budgetClosed'] ?? false,

      // budgetClosedAt can be null — so we check before converting
      // If null, we just store null. If not null, we convert the Timestamp
      budgetClosedAt: json['budgetClosedAt'] != null
          ? _parseDate(json['budgetClosedAt'])
          : null,

      createdAt: _parseDate(json['createdAt']),
      reportStatus: json['reportStatus'] ?? 'draft',
      reportRevisionNote: json['reportRevisionNote'] ?? '',
    );
  }

  // --- toJson ---
  // This converts our EventModel back into a Map so we can save it to Firestore
  // Think of it as filling out the Firestore form from our object
  Map<String, dynamic> toJson() {
    return {
      'clubId': clubId,
      'tenureId': tenureId,
      'name': name,
      'description': description,
      'date': date,           // Firestore automatically converts DateTime to Timestamp
      'endDate': endDate,
      'durationHours': durationHours,
      'venue': venue,
      'type': type,
      'totalRegistrations': totalRegistrations,
      'totalAttendees': totalAttendees,
      'budgetClosed': budgetClosed,
      'budgetClosedAt': budgetClosedAt, // This is fine as null — Firestore handles it
      'createdAt': createdAt,
      'reportStatus': reportStatus,
      'reportRevisionNote': reportRevisionNote,
    };
  }

  static DateTime _parseDate(dynamic value) {
  if (value == null) return DateTime.now();
  try { return value.toDate(); } catch (_) {}
  if (value is String) return DateTime.tryParse(value) ?? DateTime.now();
  return DateTime.now();
}
}