// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfDbF-8ZYUjiEKu9VVSlocf8YtZIzu-0',
    appId: '1:1007543007955:web:26452ea0929d4cf3673226',
    messagingSenderId: '1007543007955',
    projectId: 'club-management-app-7e0d5',
    authDomain: 'club-management-app-7e0d5.firebaseapp.com',
    storageBucket: 'club-management-app-7e0d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFujxbuziDr5zaieeAloPkimfXtnz2ZNM',
    appId: '1:1007543007955:android:983e81ccb40e3b20673226',
    messagingSenderId: '1007543007955',
    projectId: 'club-management-app-7e0d5',
    storageBucket: 'club-management-app-7e0d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGxDaoJA49halEJPitVUkOwjEOexDZvD4',
    appId: '1:1007543007955:ios:f86a11a46db54496673226',
    messagingSenderId: '1007543007955',
    projectId: 'club-management-app-7e0d5',
    storageBucket: 'club-management-app-7e0d5.firebasestorage.app',
    iosBundleId: 'com.example.clubManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGxDaoJA49halEJPitVUkOwjEOexDZvD4',
    appId: '1:1007543007955:ios:f86a11a46db54496673226',
    messagingSenderId: '1007543007955',
    projectId: 'club-management-app-7e0d5',
    storageBucket: 'club-management-app-7e0d5.firebasestorage.app',
    iosBundleId: 'com.example.clubManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHfDbF-8ZYUjiEKu9VVSlocf8YtZIzu-0',
    appId: '1:1007543007955:web:3bb1a6a4eb8b36d8673226',
    messagingSenderId: '1007543007955',
    projectId: 'club-management-app-7e0d5',
    authDomain: 'club-management-app-7e0d5.firebaseapp.com',
    storageBucket: 'club-management-app-7e0d5.firebasestorage.app',
  );
}
